sonar.projectKey=heyallensu_Global-360-auto-healing-web-tier
sonar.organization=heyallensu
sonar.sources=.
sonar.exclusions=**/.terraform/**,**/*.tfstate,**/*.tfstate.*,**/*.tfplan,**/*.tfplan.*
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
sonar.issue.ignore.multicriteria=dockerPin,albLogs,stateLogs,httpListener,snsEncryption
sonar.issue.ignore.multicriteria.dockerPin.ruleKey=docker:S8431
sonar.issue.ignore.multicriteria.dockerPin.resourceKey=docker/Dockerfile
sonar.issue.ignore.multicriteria.albLogs.ruleKey=terraform:S6258
sonar.issue.ignore.multicriteria.albLogs.resourceKey=modules/alb/main.tf
sonar.issue.ignore.multicriteria.stateLogs.ruleKey=terraform:S6258
sonar.issue.ignore.multicriteria.stateLogs.resourceKey=bootstrap/main.tf
sonar.issue.ignore.multicriteria.httpListener.ruleKey=terraform:S5332
sonar.issue.ignore.multicriteria.httpListener.resourceKey=modules/alb/main.tf
sonar.issue.ignore.multicriteria.snsEncryption.ruleKey=terraform:S6327
sonar.issue.ignore.multicriteria.snsEncryption.resourceKey=modules/alb/main.tf
