sonar.projectKey=heyallensu_Global-360-auto-healing-web-tier
sonar.organization=heyallensu
sonar.sources=.
sonar.exclusions=**/.terraform/**,**/*.tfstate,**/*.tfstate.*,**/*.tfplan,**/*.tfplan.*
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
